---
- name : only for node inf
  hosts: demo
  become: no
  gather_facts: yes
  tasks:
   - name: here is gid for local user
     debug:
      msg: "{{ansible_user_gid}}"
  tasks:
   - name: here is gid for local user
     debug:
      msg: "{{ansible_os_family}}"