- name: Installation of my web-server
  hosts: 65.0.12.7
  #hosts: all
  become: yes
  tasks:
    # - name: install web package
    #   package:
    #     name: httpd
    #     state: latest
    #   when: ansible_os_family == "RedHat"
  
    - name: install web package
      package:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    # - name: start httpd
    #   systemd:
    #     name: httpd
    #     state: started
    #   when: ansible_os_family == "RedHat"

    - name: start apache2
      systemd:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
    - name: enable apache2
      service:
        name: apache2
        enabled: yes
      when: ansible_os_family == "Debian"
    
    - name: stopapache2
       package:
         name: apache2
         state: absent
         update_cache: yes
      when: ansible_os_family == "Debian"
    
    
    # - name: start apache2
    #   systemctl:
    #     name: apache2
    #     state: enabled
    #   when: ansible_os_family == "Debian"  