# - name: Installation of my web-server
#   hosts: all
#   tasks:
#     - name: install web package
#       package:
#         name: apache2
#         state: present
#         update_cache: yes
#       when: ansible_os_family == "Debian"

#     - name: install web package
#       package:
#         name: apache2
#         state: latest
#         update_cache: yes
#       when: ansible_os_family == "Debian"

- name: Install Apache
  hosts: all
  become: true
  
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
  
  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes
    
    - name: start apache2
      systemd:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
    - name: enable apache2
      systemd:
        name: apache2
        state: enable
      when: ansible_os_family == "Debian"
    - name: euninstall apache2
      systemd:
        name: apache2
        state: absent
      when: ansible_os_family == "Debian"  